# Generated by Django 4.2.5 on 2023-09-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность сотрудника', 'verbose_name_plural': 'Должности сотрудников'},
        ),
    ]
