# Generated by Django 4.2.5 on 2023-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('active', 'В работе'), ('completed', 'Завершена')], default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
