# Generated by Django 4.2.5 on 2023-10-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
